#!/bin/bash

export JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"
export SPARK_HOME="/spark/spark-2.4.3-bin-hadoop2.7"

if [ -z $MASTER_URL ]; then
    $SPARK_HOME/sbin/start-master.sh 
else
    $SPARK_HOME/sbin/start-slave.sh $MASTER_URL
fi

while true; do
    pgrep -f hadoop
    if [ "$?" != "0" ]; then
        break
    fi
    sleep 10
done

